P = {}
P['papa-leo-13'] = dict(name='Pope Leo XIII', cat='The pope of workers and of the rosary', born='Carpineto Romano',
 bio='In the middle of the industrial revolution he wrote Rerum Novarum, defending the rights of workers; it is counted as the start of Catholic social teaching. He lived to the age of 93.',
 secs=[['Rerum Novarum', 'The encyclical he issued in 1891 defended workers’ rights to a fair wage, to rest and to form unions; it criticised both unbridled capitalism and the socialism that wanted to abolish private property.'],
       ['The rosary pope', 'He wrote eleven encyclicals on the rosary and proposed October as the month of the rosary.'],
       ['Back to St. Thomas', 'In the encyclical Aeterni Patris he put forward the philosophy of St. Thomas Aquinas as the foundation of Catholic schools.'],
       ['His link to Leo XIV', 'Leo XIV, elected in 2025, said he chose his name in his memory: just as Leo XIII answered the industrial revolution, the Church today must answer the questions of the age of artificial intelligence.']],
 docs=[['Aeterni Patris', '1879', 'On the philosophy of St. Thomas Aquinas.'],
       ['Supremi Apostolatus Officio', '1883', 'The first of his encyclicals on the rosary.'],
       ['Rerum Novarum', '1891', 'The rights of workers; the start of Catholic social teaching.'],
       ['Providentissimus Deus', '1893', 'On the study of Holy Scripture.']])
P['papa-pius-10'] = dict(name='Pope Pius X', cat='The pope of the Eucharist · Saint', born='Riese (near Venice)',
 bio='He came from a poor village family and rose from village priest to pope. He allowed children to make their First Communion at an early age.',
 secs=[['Frequent Communion', 'Until then children usually made their First Communion at 12 to 14. In 1910 Pius X laid down that children could receive Communion once they reached the age of reason, about seven, and he encouraged the faithful to receive Communion often.'],
       ['To restore all things in Christ', 'His motto as pope was “To restore all things in Christ”. He began the work of gathering the Church’s law into a single code; it was completed in 1917.'],
       ['His death and canonisation', 'He died in the first days of the First World War, broken by the suffering of the war. He was declared a saint in 1954.']],
 docs=[['Pascendi Dominici Gregis', '1907', 'Against the current of thought called Modernism.'],
       ['Quam Singulari', '1910', 'First Communion for children at an early age.']])
P['papa-benedictus-15'] = dict(name='Pope Benedict XV', cat='The pope of peace', born='Genoa',
 bio='He was elected at the start of the First World War and called the war “a senseless slaughter”. There is a statue of him in Istanbul, put up by the Turks.',
 secs=[['In the war years', 'In 1917 he put a concrete peace plan to the warring powers; it was not accepted. Through the Vatican he arranged for news to reach the families of prisoners of war and for wounded prisoners to be exchanged.'],
       ['His link to Turkey', 'During the war he helped those who suffered, whatever their religion or nation. For this, in 1921, people of different faiths and nations in Istanbul paid for a statue of him in the garden of the Cathedral of the Holy Spirit in Harbiye. The inscription on its base honours him as “the benefactor of the peoples, without distinction of nationality or religion”.'],
       ['Canon law', 'In 1917 he promulgated the first Code of Canon Law, begun by Pius X.']],
 docs=[['Ad Beatissimi Apostolorum', '1914', 'The causes of the war and a call to peace.'],
       ['Maximum Illud', '1919', 'The missions and the training of local priests.']])
P['papa-pius-11'] = dict(name='Pope Pius XI', cat='Founder of Vatican City State', born='Desio (near Milan)',
 bio='Vatican City State was founded in his time. He wrote outspoken encyclicals against both Nazism and communism.',
 secs=[['The Lateran Treaty', 'The treaty signed with Italy in 1929 founded Vatican City State and settled the “Roman Question” that had dragged on since 1870.'],
       ['Christ the King', 'In 1925 he instituted the feast of Christ the King: however strong states and ideologies may seem, the last word belongs to Christ.'],
       ['Against totalitarian regimes', 'In 1937 the encyclical Mit brennender Sorge (With burning concern), written in German, was smuggled into Germany and read out in every church; it criticised Nazi ideology. A few days later came the encyclical Divini Redemptoris against communism.']],
 docs=[['Quas Primas', '1925', 'The feast of Christ the King.'],
       ['Casti Connubii', '1930', 'On Christian marriage.'],
       ['Quadragesimo Anno', '1931', 'The social order, forty years after Rerum Novarum.'],
       ['Mit brennender Sorge', '1937', 'A critique of Nazism.'],
       ['Divini Redemptoris', '1937', 'A critique of atheistic communism.']])
P['papa-pius-12'] = dict(name='Pope Pius XII', cat='The pope of the Second World War years', born='Rome',
 bio='He was elected just before the Second World War. He defined the Assumption of Mary as a truth of faith.',
 secs=[['The war years', 'His papacy fell in the darkest years of the war. During the war many Jews in Rome were hidden in Church institutions. The pope’s conduct during the war is still debated among historians; the Vatican archives were opened to researchers in 2020.'],
       ['The Assumption of Mary', 'In 1950 he defined as a truth of faith that at the end of her earthly life Mary was taken up body and soul into heaven. The feast is kept every year on 15 August.'],
       ['Biblical studies', 'The encyclical Divino Afflante Spiritu of 1943 encouraged Catholic scholars to study the Bible in its original languages and its historical setting.']],
 docs=[['Mystici Corporis', '1943', 'The Church, the Body of Christ.'],
       ['Divino Afflante Spiritu', '1943', 'Biblical studies.'],
       ['Humani Generis', '1950', 'Faith and modern thought.'],
       ['Munificentissimus Deus', '1950', 'The Assumption of Mary.']])
P['papa-ioannes-23'] = dict(name='Pope John XXIII', cat='“The pope who loved the Turks” · Saint', born='Sotto il Monte (Bergamo)',
 bio='Before becoming pope he lived in Istanbul for ten years and learned Turkish. He is the pope who called the Second Vatican Council.',
 secs=[['The Istanbul years', 'From 1935 to 1944 Angelo Roncalli lived in Istanbul as the Vatican’s representative to Turkey and Greece. He learned Turkish and began having some prayers said in Turkish in the cathedral in Harbiye. He is known to have helped many Jews fleeing Europe during the Second World War. In Turkey he is remembered as “the pope who loved the Turks”; a street in Istanbul bears his name and there is a statue of him in the garden of the Basilica of St. Anthony.'],
       ['The Second Vatican Council', 'He was elected at 77, expected to be a caretaker pope. But three months later, to the surprise of the whole world, he announced that he would call a council. The Second Vatican Council opened on 11 October 1962.'],
       ['“The Good Pope”', 'He was loved for his warmth and humour; the Italians called him “the good pope”. In 2014 he was declared a saint on the same day as John Paul II.']],
 docs=[['Mater et Magistra', '1961', 'The Church and social justice.'],
       ['Pacem in Terris', '1963', 'Peace on earth; the first encyclical addressed “to all men of good will”.']])
P['papa-paulus-6'] = dict(name='Pope Paul VI', cat='The pope who completed the Council · Saint', born='Concesio (Brescia)',
 bio='He brought the Second Vatican Council to a close. He was the first pope to fly to five continents; in 1967 he visited Istanbul and Ephesus.',
 secs=[['Completing the Council', 'In 1965 he closed the Second Vatican Council and began putting its decisions into practice.'],
       ['Reconciliation with the Orthodox', 'In 1964 he embraced Ecumenical Patriarch Athenagoras in Jerusalem. On 7 December 1965 Rome and Constantinople lifted at the same moment the excommunications they had pronounced on each other in 1054.'],
       ['His link to Turkey', 'In July 1967 he came to Turkey: in Istanbul he visited Athenagoras at the Ecumenical Patriarchate in Fener, then went to the House of the Virgin Mary near Ephesus and to İzmir.'],
       ['Canonisation', 'He was declared a saint by Pope Francis in 2018.']],
 docs=[['Populorum Progressio', '1967', 'The development of peoples and justice.'],
       ['Humanae Vitae', '1968', 'Human life and the meaning of love in marriage.'],
       ['Evangelii Nuntiandi', '1975', 'Proclaiming the Gospel in our time.']])
P['papa-ioannes-paulus-1'] = dict(name='Pope John Paul I', cat='The smiling pope · Blessed', born='Canale d’Agordo',
 bio='His papacy lasted only 33 days. For his simple, warm manner he was called “the smiling pope”.',
 secs=[['33 days', 'Albino Luciani was elected on 26 August 1978 and was the first pope to take the names of both his predecessors. He died in his sleep on 28 September 1978.'],
       ['His style', 'He explained things simply, as if talking to children. He preferred to say “I” rather than the formal papal “we”, and he did without a coronation.'],
       ['Beatification', 'He was beatified by Pope Francis in 2022.']],
 docs=[])
P['papa-benedictus-16'] = dict(name='Pope Benedict XVI', cat='The pope of faith and reason', born='Marktl (Bavaria)',
 bio='Joseph Ratzinger, one of the leading theologians of the century. He became the first pope in about 600 years to step down of his own will.',
 secs=[['The theologian', 'At the Second Vatican Council he was a young adviser. For many years he headed the Congregation for the Doctrine of the Faith and led the preparation of the Catechism of the Catholic Church. As pope he wrote the three volumes of “Jesus of Nazareth”.'],
       ['His link to Turkey', 'In November 2006 he visited Turkey: Ankara, the House of the Virgin Mary near Ephesus, and Istanbul. In Istanbul he visited the Sultan Ahmed Mosque.'],
       ['Stepping down', 'In 2013, because of his age and strength, he stepped down. He lived in prayer in a monastery in the Vatican and died on 31 December 2022.']],
 docs=[['Deus Caritas Est', '2005', 'God is love.'],
       ['Spe Salvi', '2007', 'Saved in hope.'],
       ['Caritas in Veritate', '2009', 'Love in truth; the global economy and the human person.']])
P['papa-franciscus'] = dict(name='Pope Francis', cat='The first pope from the Americas', born='Buenos Aires',
 bio='The Argentine Jesuit Jorge Mario Bergoglio. He was the first pope to take the name of St. Francis of Assisi, and he put the poor and mercy at the centre.',
 secs=[['His life', 'He was born in Buenos Aires into a family of Italian immigrants. He became a Jesuit, and as archbishop of the city he was known as a bishop who took the bus and visited the slums.'],
       ['Mercy', 'He declared 2015-2016 a Year of Mercy. Throughout his papacy he said the Church should turn to the wounded like “a field hospital”.'],
       ['His link to Turkey', 'In November 2014 he visited Ankara and Istanbul and prayed together with Ecumenical Patriarch Bartholomew.'],
       ['His death', 'He died on 21 April 2025, Easter Monday. The day before he had given the Easter blessing.']],
 docs=[['Lumen Fidei', '2013', 'The light of faith; an encyclical begun by Benedict XVI.'],
       ['Evangelii Gaudium', '2013', 'The joy of the Gospel (apostolic exhortation).'],
       ['Laudato Si’', '2015', 'On care for our common home.'],
       ['Fratelli Tutti', '2020', 'Fraternity and social friendship.'],
       ['Dilexit Nos', '2024', 'The love of the Sacred Heart of Jesus.']])
P['papa-leo-14'] = dict(name='Pope Leo XIV', cat='Current Pontiff', born='Chicago',
 bio='Robert Francis Prevost was elected on 8 May 2025. He is the first pope from the United States and worked for many years as a missionary in Peru. He is an Augustinian friar.',
 secs=[['His life', 'He was born in Chicago in 1955. He joined the Order of St. Augustine, worked in Peru as a missionary and teacher, and later became prior general of his order. In 2015 he became bishop of Chiclayo in Peru, and in 2023 head of the Vatican office responsible for bishops.'],
       ['The name Leo', 'He said he chose his name in memory of Leo XIII: just as Leo answered the industrial revolution, the Church today must answer the questions the age of artificial intelligence raises about human dignity and work.'],
       ['His link to Turkey', 'In November 2025, for the 1700th anniversary of the Council of Nicaea, he came to Turkey and prayed together with Ecumenical Patriarch Bartholomew in İznik.']],
 docs=[['Dilexi Te', '2025', 'An apostolic exhortation on love for the poor; a text begun by Pope Francis.']])
