# Twelve more popes with unusual stories, merged into the line by "ord".
MORE4 = [
 {"id": "papa-callixtus-1", "ord": 16, "name": "Papa I. Callixtus", "years": "217-222", "born": "Roma", "tone": "green",
  "cat": "Köleyken papa olan şehit · Aziz",
  "bio": "Gençliğinde bir köleydi; madenlerde cezasını çekti, sonra Roma Kilisesi’nin başına geçti. Adını taşıyan yeraltı mezarlığı bugün Roma’nın en çok ziyaret edilen katakomplarındandır.",
  "secs": [["Kölelikten papalığa", "Hristiyan bir efendinin kölesiyken bir bankacılık işinde zarara uğradı ve Sardinya madenlerine sürüldü. Serbest kalınca Papa Zephyrinus onu Via Appia’daki Hristiyan mezarlığının yönetimine getirdi; bu mezarlık bugün Aziz Callixtus Katakombu diye bilinir."],
           ["Merhametin papası", "Tövbe eden büyük günahkârların Kilise’ye yeniden kabul edilmesini savundu. Bu tutumu, sert bir çizgi savunan Hippolytus ile arasında derin bir anlaşmazlığa yol açtı. Yaklaşık 222’de şehit edildi."]],
  "docs": []},
 {"id": "papa-martinus-1", "ord": 74, "name": "Papa I. Martinus", "years": "649-655", "born": "Todi", "tone": "red",
  "cat": "İstanbul’da yargılanan şehit papa · Aziz",
  "bio": "İmparatora karşı Mesih’teki iki iradeyi savundu; tutuklanıp Konstantinopolis’te yargılandı ve sürgünde öldü. Şehit olarak anılan son papadır.",
  "secs": [["Laterano Sinodu", "649’da Roma’da topladığı sinodda, İmparator II. Konstans’ın bu tartışmayı yasaklayan fermanına rağmen Mesih’in hem Tanrısal hem insani iradesi olduğunu açıkça ilan etti."],
           ["Türkiye ile bağı", "653’te imparatorun askerleri onu Roma’da tutuklayıp Konstantinopolis’e getirdi. Hasta hâliyle yargılandı, zincirlerle sokaklarda dolaştırıldı ve Kırım’daki Kherson’a sürüldü. 655’te orada öldü; mektuplarında açlıktan ve yalnızlıktan söz eder."]],
  "docs": []},
 {"id": "papa-sergius-1", "ord": 84, "name": "Papa I. Sergius", "years": "687-701", "born": "Palermo", "tone": "teal",
  "cat": "Antakyalı bir ailenin oğlu · Aziz",
  "bio": "Antakya’dan Sicilya’ya göç etmiş Süryani bir ailenin oğluydu. Bugün her ayinde söylenen “Tanrı’nın Kuzusu” (Agnus Dei) duasını ayine o ekledi.",
  "secs": [["Tanrı’nın Kuzusu", "Ekmeğin bölünmesi sırasında söylenen “Ey dünyanın günahlarını kaldıran Tanrı Kuzusu” duasını Roma ayinine kattı. Meryem bayramlarında yapılan alayları da o başlattı."],
           ["Türkiye ile bağı", "692’de Konstantinopolis’teki Trullo Sinodu’nun bazı kararlarını imzalamayı reddetti. İmparator II. Justinianus onu tutuklatmak için bir subay gönderdi; ama Roma ve Ravenna halkı ve askerleri papayı korudu ve subay papanın yatağının altına saklanarak canını kurtardı."]],
  "docs": []},
 {"id": "papa-zacharias", "ord": 91, "name": "Papa Zacharias", "years": "741-752", "born": "Calabria", "tone": "blue",
  "cat": "Rum asıllı papa · Aziz",
  "bio": "Rum asıllı papaların sonuncularındandı. Barışçı diplomasisiyle Roma’yı Lombard saldırılarından korudu.",
  "secs": [["Barış elçisi", "Lombard kralı Liutprand ile bizzat görüşmeye gitti ve savaşmadan, ele geçirilmiş şehirlerin geri verilmesini sağladı."],
           ["İki dünya arasında", "Papa I. Gregorius’un “Diyaloglar” adlı eserini Yunancaya çevirerek Doğu’daki Hristiyanlara ulaştırdı. Batı’da ise Frank kralı Pepin ile kurduğu bağ, Avrupa’nın sonraki yüzyıllarını etkiledi."]],
  "docs": []},
 {"id": "papa-formosus", "ord": 111, "name": "Papa Formosus", "years": "891-896", "born": "Roma", "tone": "purple",
  "cat": "Bulgaristan misyoneri · “Ceset Sinodu”",
  "bio": "Gençliğinde Bulgarlara İncil’i anlatan bir misyonerdi. Ölümünden sonra cesedi mezarından çıkarılıp yargılandı; tarihe “Ceset Sinodu” olarak geçen bu olay, Kilise’nin en karanlık dönemlerinden birinin simgesidir.",
  "secs": [["Bulgaristan’da", "866’da Papa I. Nicolaus onu, yeni Hristiyan olan Bulgarlara piskopos olarak gönderdi. Kral Boris onu o kadar sevdi ki Bulgaristan’ın başpiskoposu olmasını istedi."],
           ["Ceset Sinodu", "897’de halefi VI. Stephanus, siyasi kin yüzünden Formosus’un cesedini mezardan çıkartıp papalık giysileriyle bir tahta oturttu ve yargıladı. Halk bu rezalete öfkelendi; Stephanus aynı yıl tahttan indirildi. Sonraki papalar Formosus’un itibarını iade etti."]],
  "docs": []},
 {"id": "papa-silvester-2", "ord": 139, "name": "Papa II. Silvester", "years": "999-1003", "born": "Auvergne", "tone": "indigo",
  "cat": "Bilim insanı papa · 1000 yılının papası",
  "bio": "Matematikçi, gökbilimci ve öğretmendi. Arap rakamlarını ve abaküsü Batı Avrupa’ya tanıtanlardan biriydi; 1000 yılına papa olarak girdi.",
  "secs": [["Gerbert", "Asıl adı Gerbert’ti. Gençliğinde İspanya’da, Endülüs’ün bilgisinin aktığı manastırlarda matematik ve gökbilim öğrendi. Reims’teki okulunda gök kürelerini ve abaküsü derslerde kullandı."],
           ["İlk Fransız papa", "999’da seçilen ilk Fransız papadır. Macaristan’ın ve Polonya’nın Kilise yapısını kurarak Orta Avrupa’nın Hristiyan dünyasına katılmasında rol oynadı."]],
  "docs": []},
 {"id": "papa-hadrianus-4", "ord": 169, "name": "Papa IV. Hadrianus", "years": "1154-1159", "born": "Abbots Langley, İngiltere", "tone": "gold",
  "cat": "Tek İngiliz papa",
  "bio": "Nicholas Breakspear adıyla doğdu; bugüne kadar papa olan tek İngiliz’dir. Fransa’da bir manastıra sıradan bir keşiş olarak girdi ve oranın başrahipliğine, oradan da papalığa yükseldi.",
  "secs": [["İskandinavya’da", "Papa olmadan önce elçi olarak Norveç ve İsveç’e gitti; 1152’de Norveç Kilisesi’nin ilk başpiskoposluğunu kurdu."],
           ["İmparatorla", "1155’te Frederick Barbarossa’yı imparator olarak taçlandırdı; ama kısa sürede papa ile imparator arasında uzun sürecek bir güç mücadelesi başladı."]],
  "docs": []},
 {"id": "papa-ioannes-21", "ord": 187, "name": "Papa XXI. Ioannes", "years": "1276-1277", "born": "Lizbon", "tone": "teal",
  "cat": "Hekim papa · Tek Portekizli papa",
  "bio": "Ünlü bir hekim ve mantıkçıydı; yazdığı tıp kitabı yüzyıllarca okundu. Papalığının sekizinci ayında çalışma odasının tavanı üzerine çöktü.",
  "secs": [["İspanyalı Petrus", "Petrus Hispanus adıyla tanınır. Mantık üzerine yazdığı ders kitabı yüzyıllarca üniversitelerde okutuldu; “Yoksulların Hazinesi” adlı tıp kitabı ise sıradan insanlar için pratik tedaviler içeriyordu."],
           ["Viterbo’da", "Viterbo’daki sarayına çalışmak için ek bir oda yaptırdı. 1277 Mayısında bu odanın tavanı çöktü ve birkaç gün sonra öldü."]],
  "docs": [["Summulae Logicales", "13. yüzyıl", "Orta Çağ üniversitelerinin temel mantık kitabı."]]},
 {"id": "papa-callixtus-3", "ord": 209, "name": "Papa III. Callixtus", "years": "1455-1458", "born": "Xàtiva, Valencia", "tone": "orange",
  "cat": "Öğle çanlarının papası",
  "bio": "Öğle vakti çalan kilise çanlarının geleneği onun bir çağrısına bağlanır. Jeanne d’Arc’ın davasını yeniden açtırıp onu aklattı.",
  "secs": [["Öğle çanları", "1456’da Belgrad kuşatması sırasında bütün Hristiyanların öğle vakti çan sesiyle birlikte dua etmesini istedi. Belgrad’dan gelen haberle bu çan, öğle vakti dua çağrısı olarak yerleşti; Melek Duası ile birlikte bugün de sürer."],
           ["Jeanne d’Arc", "1431’de yakılan Jeanne d’Arc’ın davasının yeniden görülmesini emretti; 1456’da mahkeme onun masum olduğunu ilan etti. Jeanne 1920’de aziz ilan edildi."]],
  "docs": []},
 {"id": "papa-pius-2", "ord": 210, "name": "Papa II. Pius", "years": "1458-1464", "born": "Corsignano (Pienza)", "tone": "purple",
  "cat": "Yazar papa · Fatih’e mektup",
  "bio": "Rönesans’ın ünlü yazarlarındandı; kendi hayatını anlatan tek papadır. Fatih Sultan Mehmed’e hitaben uzun bir mektup kaleme aldı.",
  "secs": [["Enea Silvio", "Gençliğinde şiirler ve bir aşk romanı yazdı; diplomat olarak Avrupa’yı dolaştı. Papa olunca anılarını “Commentarii” adıyla yazdı. Doğduğu köyü yeniden düzenletip Pienza adını verdi; burası bir Rönesans şehri olarak bugün UNESCO Dünya Mirası’dır."],
           ["Türkiye ile bağı", "1461’de Fatih Sultan Mehmed’e hitaben, onu Hristiyan olmaya davet eden uzun bir mektup yazdı; mektubun gönderilip gönderilmediği bilinmez. 1464’te Ankona’da, beklediği donanmanın gelmesini beklerken öldü."]],
  "docs": [["Commentarii", "1464", "Bir papanın kaleminden çıkmış tek otobiyografi."]]},
 {"id": "papa-urbanus-8", "ord": 235, "name": "Papa VIII. Urbanus", "years": "1623-1644", "born": "Floransa", "tone": "gold",
  "cat": "Bernini’nin papası · Galileo davasının papası",
  "bio": "Gençliğine ait bir portresi Caravaggio’ya atfedilir; papa olunca Bernini’ye Aziz Petrus Bazilikası’nın görkemli baldakenini. Galileo davası onun döneminde görüldü.",
  "secs": [["Sanatın papası", "Maffeo Barberini, 1626’da yeni Aziz Petrus Bazilikası’nı kutsadı. Bernini’nin bronz baldakeni ve Barberini Sarayı onun döneminin eserleridir."],
           ["Galileo", "Galileo ile önce dosttu; ama 1632’de yayımlanan “Diyalog” kitabı üzerine Galileo 1633’te yargılandı ve ev hapsine mahkûm edildi. Kilise, 1992’de II. Ioannes Paulus’un konuşmasıyla bu davadaki hataları kabul etti."]],
  "docs": []},
 {"id": "papa-clemens-14", "ord": 249, "name": "Papa XIV. Clemens", "years": "1769-1774", "born": "Santarcangelo di Romagna", "tone": "blue",
  "cat": "Cizvitleri kapatan papa",
  "bio": "Fransisken bir rahipti. Avrupa krallarının baskısıyla 1773’te Cizvit Tarikatı’nı kaldırdı; Vatikan’daki Pio-Clementino Müzesi’ni kurdu.",
  "secs": [["Cizvitler", "Portekiz, İspanya ve Fransa kralları Cizvitlerin kaldırılmasını istiyordu. Clemens uzun tereddüdün ardından 1773’te “Dominus ac Redemptor” ile tarikatı kapattı. Tarikat 1814’te VII. Pius tarafından yeniden kuruldu."],
           ["Müze", "Antik heykelleri sergilemek için Vatikan’da bugünkü Vatikan Müzeleri’nin çekirdeğini oluşturan Pio-Clementino Müzesi’ni kurdu."]],
  "docs": [["Dominus ac Redemptor", "1773", "Cizvit Tarikatı’nı kaldıran papalık belgesi."]]},
]
