# Fifteen more popes, merged into the line by "ord".
MORE3 = [
 {"id": "papa-hormisdas", "ord": 52, "name": "Papa Hormisdas", "years": "514-523", "born": "Frosinone", "tone": "teal",
  "cat": "Doğu ile barışın papası · Aziz",
  "bio": "Roma ile Konstantinopolis arasındaki otuz beş yıllık ayrılığı, kendi adıyla anılan inanç formülüyle sona erdirdi.",
  "secs": [["Akakios ayrılığı", "484’te Roma ile Konstantinopolis Kilisesi’nin bağı koptu. Hormisdas, Doğu’ya elçiler göndererek bu kırgınlığı sabırla onarmaya çalıştı."],
           ["Türkiye ile bağı", "519’da Konstantinopolis Patriği II. Yuhanna ve İmparator I. Justinus, “Hormisdas Formülü”nü imzaladı. Formül, Roma Kilisesi’nde Katolik inancın her zaman lekesiz korunduğunu kabul ediyordu. Böylece İstanbul ile Roma yeniden birleşti."]],
  "docs": [["Hormisdas Formülü", "519", "Doğu piskoposlarının imzaladığı, Petrus’un makamına bağlılığı dile getiren inanç metni."]]},
 {"id": "papa-agatho", "ord": 79, "name": "Papa Agatho", "years": "678-681", "born": "Sicilya", "tone": "purple",
  "cat": "III. Konstantinopolis Konsili’nin papası · Aziz",
  "bio": "Mesih’in hem Tanrısal hem insani bir iradesi olduğunu açıklayan mektubu, İstanbul’da toplanan konsilde coşkuyla okundu.",
  "secs": [["İki irade", "O dönemde bazıları Mesih’te yalnızca tek bir irade bulunduğunu öğretiyordu. Agatho, Mesih’in gerçek Tanrı ve gerçek insan olduğu için iki iradesi bulunduğunu, insani iradesinin Tanrısal iradeye özgürce boyun eğdiğini açıkladı."],
           ["Türkiye ile bağı", "680-681’de Konstantinopolis’te toplanan VI. Ekümenik Konsil’de mektubu okununca konsil babaları “Petrus, Agatho aracılığıyla konuştu” diye seslendi."]],
  "docs": [["İmparatora mektup", "680", "Mesih’teki iki iradeyi açıklayan ve konsilde okunan dogmatik mektup."]]},
 {"id": "papa-hadrianus-1", "ord": 95, "name": "Papa I. Hadrianus", "years": "772-795", "born": "Roma", "tone": "gold",
  "cat": "II. İznik Konsili’nin papası",
  "bio": "Yirmi üç yıllık papalığı, Petrus’tan sonraki en uzun papalıklardan biridir. Kutsal ikonalara saygıyı yeniden tesis eden İznik Konsili onun döneminde toplandı.",
  "secs": [["Türkiye ile bağı", "787’de İznik’te toplanan VII. Ekümenik Konsil’e temsilcilerini gönderdi. Konsil, ikonaların yok edilmesine son verdi ve tasvirlere gösterilen saygının, tasvir edilen kişiye yöneldiğini açıkladı."],
           ["Şarlman", "Frank kralı Şarlman ile yakın dosttu. Onun ölümüne üzülen Şarlman, Hadrianus için mermer bir mezar yazıtı hazırlattı; yazıt bugün Aziz Petrus Bazilikası’ndadır."]],
  "docs": []},
 {"id": "papa-nicolaus-1", "ord": 105, "name": "Papa I. Nicolaus", "years": "858-867", "born": "Roma", "tone": "indigo",
  "cat": "“Büyük” Nicolaus · Aziz",
  "bio": "Evliliğin bozulmazlığını krallara karşı savundu, Bulgarlara yazdığı uzun cevaplarla bir halkın Hristiyanlaşmasına rehberlik etti.",
  "secs": [["Bulgarlara cevaplar", "866’da Bulgar Kralı Boris, yeni Hristiyan olan halkı için yüzden fazla soru gönderdi. Nicolaus’un cevapları; vaftiz, oruç, evlilik ve adalet üzerine yumuşak ve pratik öğütlerle doludur. İşkenceyle itiraf almanın yasak olduğunu da bu mektupta yazar."],
           ["Türkiye ile bağı", "Konstantinopolis Patriği İgnatios’un haksız yere görevden alınmasına karşı çıktı. Bu anlaşmazlık, Roma ile İstanbul arasında uzun sürecek gerginliklerin ilk adımlarından biri oldu."]],
  "docs": [["Responsa ad consulta Bulgarorum", "866", "Bulgarların sorularına verilen 106 cevap."]]},
 {"id": "papa-leo-9", "ord": 152, "name": "Papa IX. Leo", "years": "1049-1054", "born": "Egisheim, Alsas", "tone": "red",
  "cat": "Reform papası · Aziz",
  "bio": "Avrupa’yı baştan başa dolaşarak Kilise’yi rüşvet ve dünyevilikten arındırmaya çalıştı. Papalığının sonu, Doğu ile Batı arasındaki 1054 kopuşuyla gölgelendi.",
  "secs": [["Yollarda bir papa", "Beş yıllık papalığının büyük bölümünü yolda geçirdi; İtalya, Fransa ve Almanya’da sinodlar topladı. Kilise makamlarının para ile alınıp satılmasına karşı kararlı bir mücadele başlattı."],
           ["Türkiye ile bağı", "1054’te Konstantinopolis’e elçiler gönderdi. Leo nisan ayında öldükten sonra, 16 Temmuz 1054’te Kardinal Humbert aforoz belgesini Ayasofya’nın sunağına bıraktı. Bu olay Doğu-Batı ayrılığının sembolü oldu; karşılıklı aforozlar 1965’te Papa VI. Paulus ve Patrik Athenagoras tarafından kaldırıldı."]],
  "docs": []},
 {"id": "papa-gregorius-10", "ord": 184, "name": "Papa X. Gregorius", "years": "1271-1276", "born": "Piacenza", "tone": "blue",
  "cat": "Konklavın kurucusu · Kutsanmış",
  "bio": "Kilise tarihinin en uzun seçimi, yaklaşık üç yıl sonra onun adıyla bitti. Haberi aldığında Akka’da hacıydı ve henüz rahip bile değildi.",
  "secs": [["Kapalı kapılar", "Bir daha bu kadar uzun bir bekleyiş yaşanmasın diye 1274’te kardinallerin kapalı bir yerde, dış dünyadan ayrı olarak papa seçmesini kural haline getirdi. “Konklav” (anahtarla kilitli oda) uygulaması bugün de bu kurala dayanır."],
           ["II. Lyon Konsili", "1274’te topladığı konsilde Bizans İmparatoru VIII. Mihail’in elçileri Roma ile birliği kabul etti. Bu birlik kısa sürdü, ama Gregorius’un en büyük umudu Doğu ile Batı’yı yeniden bir araya getirmekti."]],
  "docs": [["Ubi periculum", "1274", "Papa seçiminin kapalı konklavda yapılmasını düzenleyen anayasa."]]},
 {"id": "papa-celestinus-5", "ord": 192, "name": "Papa V. Celestinus", "years": "1294", "born": "Molise", "tone": "green",
  "cat": "Görevinden ayrılan münzevi · Aziz",
  "bio": "Dağlarda yaşayan seksen yaşındaki bir münzeviydi; papa seçildi, beş ay sonra bu yükü taşıyamayacağını görerek görevinden ayrıldı.",
  "secs": [["Morrone’lu Pietro", "Gençliğinden beri Abruzzo dağlarında dua ve oruçla yaşadı; çevresinde toplanan keşişlerle sonradan Celestinler adını alan bir topluluk kurdu."],
           ["Alçakgönüllü bir veda", "13 Aralık 1294’te papalıktan özgürce feragat etti. Papa XVI. Benedictus, 2009’da L’Aquila’daki mezarını ziyaret ederek kendi palliumunu üzerine bıraktı; dört yıl sonra kendisi de görevden ayrıldı."]],
  "docs": []},
 {"id": "papa-eugenius-4", "ord": 207, "name": "Papa IV. Eugenius", "years": "1431-1447", "born": "Venedik", "tone": "purple",
  "cat": "Floransa Konsili’nin papası",
  "bio": "Bizans İmparatoru ve Konstantinopolis Patriği ile birlikte Floransa’da masaya oturdu; 1439’da Doğu ile Batı’nın birleştiği ilan edildi.",
  "secs": [["Türkiye ile bağı", "İmparator VIII. Yuannis Palaiologos ve Patrik II. Yusuf, yüzlerce Rum din adamıyla İstanbul’dan İtalya’ya geldi. 6 Temmuz 1439’da okunan “Laetentur Caeli” (Gökler sevinsin) bildirisiyle birlik ilan edildi."],
           ["Ermeniler ve Süryaniler", "Aynı konsil 1439’da Ermeni Kilisesi ile, sonraki yıllarda Kıptîler ve Süryanilerle de birlik metinleri imzaladı. Türkiye’deki Ermeni ve Süryani Katolik toplulukların tarihi bu çabalarla da bağlantılıdır."]],
  "docs": [["Laetentur Caeli", "1439", "Rum Kilisesi ile birliği ilan eden konsil bildirisi."], ["Exultate Deo", "1439", "Ermenilerle birlik bildirisi; yedi kutsal sırrın açıklaması."]]},
 {"id": "papa-nicolaus-5", "ord": 208, "name": "Papa V. Nicolaus", "years": "1447-1455", "born": "Sarzana", "tone": "gold",
  "cat": "Vatikan Kütüphanesi’nin kurucusu",
  "bio": "Kitap tutkunu bir âlimdi. Topladığı yüzlerce el yazmasıyla Vatikan Kütüphanesi’nin temelini attı. Konstantinopolis’in düşüşü onun döneminde yaşandı.",
  "secs": [["Kitaplar", "Yunanca eserlerin Latinceye çevrilmesi için âlimlere para ödedi; öldüğünde kütüphanede binden fazla el yazması vardı."],
           ["Türkiye ile bağı", "29 Mayıs 1453’te Konstantinopolis düştü. Nicolaus, şehirden kaçan Rum âlimlerin taşıdığı kitapların korunmasına yardım etti; bu el yazmalarının bir kısmı bugün hâlâ Vatikan Kütüphanesi’ndedir."]],
  "docs": []},
 {"id": "papa-sixtus-4", "ord": 212, "name": "Papa IV. Sixtus", "years": "1471-1484", "born": "Celle Ligure", "tone": "blue",
  "cat": "Sistina Şapeli’nin papası",
  "bio": "Fransisken bir ilahiyatçıydı. Bugün papa seçimlerinin yapıldığı Sistina Şapeli onun adını taşır.",
  "secs": [["Sistina Şapeli", "1477-1481 arasında yaptırdığı şapelin duvarlarını Botticelli, Perugino ve Ghirlandaio gibi ressamlar süsledi. Tavanı ve son yargı fresklerini ise yıllar sonra Michelangelo yaptı."],
           ["Kütüphane herkese", "1475’te Vatikan Kütüphanesi’ni âlimlerin kullanımına açtı ve ilk kütüphaneciyi atadı. Kutsal Bakire’nin Lekesiz Gebeliği bayramını da kendi ayin metinleriyle onayladı."]],
  "docs": []},
 {"id": "papa-leo-10", "ord": 217, "name": "Papa X. Leo", "years": "1513-1521", "born": "Floransa", "tone": "orange",
  "cat": "Rönesans papası",
  "bio": "Medici ailesinden gelen, sanatı ve Raffaello’yu seven bir papaydı. Luther’in Reformu onun döneminde başladı.",
  "secs": [["Sanat ve borç", "Aziz Petrus Bazilikası’nın yeniden yapımı için para toplanırken endüljansların kötüye kullanılması tartışmalara yol açtı. Bu tartışma 1517’de Luther’in 95 tezinin kıvılcımı oldu."],
           ["Luther", "1520’de “Exsurge Domine” ile Luther’in kırk bir önermesini mahkûm etti; Luther geri adım atmayınca 1521’de aforoz edildi. Kilise’nin derin reformu ise sonraki papaların ve Trento Konsili’nin işi olacaktı."]],
  "docs": [["Exsurge Domine", "1520", "Luther’in önermelerini mahkûm eden bulla."]]},
 {"id": "papa-pius-4", "ord": 224, "name": "Papa IV. Pius", "years": "1559-1565", "born": "Milano", "tone": "teal",
  "cat": "Trento Konsili’ni tamamlayan papa",
  "bio": "On yıl ara verilmiş olan Trento Konsili’ni yeniden topladı ve 1563’te başarıyla tamamladı.",
  "secs": [["Trento", "Konsil, Kutsal Kitap ve Gelenek, kutsal sırlar ve aklanma hakkındaki Katolik öğretiyi açıkça tanımladı; rahip adayları için seminerler kurulmasını istedi. Pius, kararları 1564’te onayladı."],
           ["Aziz Carlo Borromeo", "Yeğeni Carlo Borromeo’yu yanına aldı. Carlo, konsilin kararlarını hayata geçiren büyük bir piskopos ve aziz oldu."]],
  "docs": [["Professio fidei Tridentina", "1564", "Trento Konsili’nden sonra okunmaya başlanan iman ikrarı."]]},
 {"id": "papa-sixtus-5", "ord": 227, "name": "Papa V. Sixtus", "years": "1585-1590", "born": "Grottammare", "tone": "gold",
  "cat": "Roma’yı yeniden kuran papa",
  "bio": "Çoban bir çocukken Fransisken oldu. Beş yılda Roma’nın yollarını, su kemerlerini ve meydanlarını yeniden düzenledi; Aziz Petrus’un kubbesi onun döneminde tamamlandı.",
  "secs": [["Kubbe ve dikilitaş", "1586’da Aziz Petrus Meydanı’nın ortasına Mısır’dan getirilmiş dikilitaşı diktirdi. 1590’da Michelangelo’nun tasarladığı kubbe Giacomo della Porta tarafından tamamlandı."],
           ["Kardinaller ve kurullar", "Kardinallerin sayısını yetmişle sınırladı ve Vatikan’ın yönetimini on beş kurula (kongregasyon) ayırdı. Bu düzen yüzyıllar boyunca kullanıldı."]],
  "docs": [["Immensa Aeterni Dei", "1588", "Roma Kûryası’nı kongregasyonlara ayıran anayasa."]]},
 {"id": "papa-innocentius-11", "ord": 240, "name": "Papa XI. Innocentius", "years": "1676-1689", "born": "Como", "tone": "green",
  "cat": "Sade yaşamın papası · Kutsanmış",
  "bio": "Kendisi çok sade yaşadı ve Vatikan’daki savurganlığı kıstı. Papalığında 1683 Viyana Kuşatması yaşandı.",
  "secs": [["Sadelik", "Akrabalarına makam ve servet dağıtma alışkanlığına son verdi, Papalık Devleti’nin borçlarını azalttı. 1956’da kutsanmış ilan edildi."],
           ["Viyana 1683", "Osmanlı ordusu Viyana’yı kuşattığında Lehistan Kralı Jan Sobieski ile İmparator I. Leopold arasındaki ittifakı destekledi ve büyük yardım gönderdi. Kuşatmanın kalkması, Avrupa tarihinde bir dönüm noktası olarak hatırlanır."]],
  "docs": []},
 {"id": "papa-gregorius-16", "ord": 254, "name": "Papa XVI. Gregorius", "years": "1831-1846", "born": "Belluno", "tone": "indigo",
  "cat": "Köle ticaretine karşı papa",
  "bio": "Kamaldoli tarikatından bir keşişti; piskopos olmadan seçilen son papadır. Köle ticaretini açıkça mahkûm etti.",
  "secs": [["Kölelik", "1839’da yayımladığı “In supremo apostolatus” ile Afrikalıların ve diğer halkların köleleştirilmesini ve köle ticaretini Hristiyanlara açıkça yasakladı."],
           ["Misyonlar", "Dünyanın dört bir yanında yeni piskoposluklar kurdu ve yerli din adamlarının yetiştirilmesini teşvik etti. Döneminde Asya, Afrika ve Amerika’daki misyonlar büyük ölçüde genişledi."]],
  "docs": [["In supremo apostolatus", "1839", "Köle ticaretini mahkûm eden apostolik mektup."], ["Mirari vos", "1832", "Dönemin fikir akımları üzerine genelge."]]},
]
