#!/usr/bin/env python3
"""Takes the Turkish out of the English site (verbumdomini.ca) after tools/build.ps1 -EnglishSite.

The shared data files carry both languages side by side. On the English site only the English is
used, so here the Turkish half of every pair is emptied in place: strings become '', lists and
objects keep their shape (the script still expects the same structure, it just never shows them).

  data/*.js           the runtime data (Bible, Qur'an and hadith popups, Catechism, saints, rosary)
  *.html  kd-refs     the passages each page embeds for its popups

Usage: python3 tools/en-site/strip_tr.py _site_en
Prints any Turkish-only letters left over, so a new field that slips through shows up at once.
"""
import json, os, re, sys

TR_LETTERS = re.compile(r'[ğışİĞŞ]')


def blank(x):
    if isinstance(x, str): return ''
    if isinstance(x, list): return [blank(v) for v in x]
    if isinstance(x, dict): return {k: blank(v) for k, v in x.items()}
    return x  # numbers (verse numbers, question numbers) stay


def strip(x):
    """The Turkish of every pair emptied: "tr" beside "en", "foo" beside "fooEn", "fooTr" beside "fooEn"."""
    if isinstance(x, list): return [strip(v) for v in x]
    if not isinstance(x, dict): return x
    out = {}
    for k, v in x.items():
        is_tr = (k == 'tr' and 'en' in x) or (k + 'En') in x or (k.endswith('Tr') and k[:-2] + 'En' in x) \
            or (k in ('title', 't', 'name') and isinstance(v, str) and isinstance(x.get('en'), str)) \
            or (k == 'note' and 'noteEn' not in x)   # editors' notes written for the Turkish only
        out[k] = blank(v) if is_tr else strip(v)
    return out


# Files whose values are plain arrays, with the Turkish at fixed positions
ARRAY_TR = {
    'SAINT_NAMES': (0,),          # [tr name, en name]
    'SAINT_SUMMARY': (0, 2),      # [tr rank, en rank, tr summary, en summary]
    'REFS_QURAN': (2,),           # each verse: [number, Arabic, tr, en]
}


def strip_named(name, data):
    for prefix, idx in ARRAY_TR.items():
        if name.startswith(prefix):
            def fix(a):
                if isinstance(a, list) and a and isinstance(a[0], list): return [fix(v) for v in a]
                return [('' if i in idx and isinstance(v, str) else v) for i, v in enumerate(a)]
            return {k: fix(v) for k, v in data.items()}
    return strip(data)


def do_js(path):
    s = open(path, encoding='utf-8').read()
    if '/*JSON-START*/' in s:
        start = s.index('/*JSON-START*/') + len('/*JSON-START*/'); end = s.index('/*JSON-END*/')
    else:
        start = re.search(r'window\.[A-Z_0-9]+\s*=\s*', s).end(); end = s.rindex(';')
    head = re.sub(r'^\s*/\*.*?\*/\s*', '', s[:start], flags=re.S)   # the bilingual comment goes
    head = head.replace('/*JSON-START*/', '')
    name = re.search(r'([A-Z_0-9]+)(?:\.parts\[\d+\])?\s*=\s*$', head).group(1)
    tail = s[end:].replace('/*JSON-END*/', '')
    data = strip_named(name, json.loads(s[start:end]))
    out = f'/* Verbum Domini, English only. Generated by tools/en-site/strip_tr.py; do not edit. */\n' \
        + head + json.dumps(data, ensure_ascii=False, separators=(',', ':')) + tail
    open(path, 'w', encoding='utf-8').write(out)


def do_html(path):
    s = open(path, encoding='utf-8').read()
    def fix(m):
        data = json.loads(m.group(2))
        data = {k: strip_named(k, v) for k, v in data.items()}
        return m.group(1) + json.dumps(data, ensure_ascii=False, separators=(',', ':')) + '</script>'
    t = re.sub(r'(<script type="application/json" id="kd-refs">)(.*?)</script>', fix, s, flags=re.S)
    if t != s: open(path, 'w', encoding='utf-8').write(t)


def main(root):
    for f in sorted(os.listdir(os.path.join(root, 'data'))):
        if f.endswith('.js'): do_js(os.path.join(root, 'data', f))
    for f in sorted(os.listdir(root)):
        if f.endswith('.html'): do_html(os.path.join(root, f))
    left = 0
    for d in (root, os.path.join(root, 'data')):
        for f in sorted(os.listdir(d)):
            if not f.endswith(('.js', '.html', '.json', '.xml', '.txt')): continue
            n = len(TR_LETTERS.findall(open(os.path.join(d, f), encoding='utf-8').read()))
            if n and not f.endswith('.min.js'): print(f'  Turkish letters left in {f}: {n}'); left += n
    print(f'  English site: Turkish taken out of the data ({left} Turkish letters left outside the script)')


if __name__ == '__main__':
    main(sys.argv[1] if len(sys.argv) > 1 else '_site_en')
